name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #1️⃣ Checkout repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      # 3️⃣ Cache SonarQube packages
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # 4️⃣ Cache Maven packages
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('backend/to-do-list/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # 5️⃣ Build and run SonarCloud analysis
      - name: Build and analyze backend
        working-directory: ./backend/to-do-list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # ✅ Added for PR decoration
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}     # already correct
        run: |
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=shimrin23_Quality_Assurance \
            -Dsonar.organization=shimrin23 \
            -Dsonar.host.url=https://sonarcloud.io    # ✅ Explicit host url added
