name: Java CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build backend
        working-directory: ./backend/to-do-list
        run: mvn clean package -DskipTests

      - name: Start application
        working-directory: ./backend/to-do-list
        run: |
          java -jar target/*.jar &
          sleep 15

      - name: Run API tests
        working-directory: ./backend/to-do-list
        run: mvn test -DbaseUrl=http://localhost:8080
