name: Java CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Build the project
      - name: Build project
        run: mvn clean package

      # Run tests
      - name: Run tests
        run: mvn test

      # Optional: Archive test reports
      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: target/surefire-reports
