# Trigger CI
name: Java CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./to-do-list

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '''17'''
        distribution: '''temurin'''
        cache: maven
    - name: Build with Maven
      run: mvn clean install
    - name: Test with Maven
      run: mvn test
