# Trigger CI
name: Java CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      working-directory: ./backend/to-do-list
      run: mvn clean package

    - name: Start Application
      working-directory: ./backend/to-do-list
      run: |
        java -jar target/*.jar &
        sleep 10 # Give the application time to start

    - name: Test with Maven
      working-directory: ./backend/to-do-list
      run: mvn -DbaseUrl=http://localhost:8080 test